import Head from 'next/head';
import { Button, Box, Typography } from '@mui/material';
import React from 'react';

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ padding: '64px' }}>
        <Box>
          <Button variant="contained" sx={{ marginRight: 2 }}>
            Contained
          </Button>
          <Button variant="outlined">Outlined</Button>
        </Box>
        <Box sx={{ marginTop: 8 }}>
          <Typography variant="h1">h1. Heading</Typography>
          <Typography variant="h2">h2. Heading</Typography>
          <Typography variant="h3">h3. Heading</Typography>
          <Typography variant="h4">h4. Heading</Typography>
          <Typography variant="h5">h5. Heading</Typography>
          <Typography variant="h6">h6. Heading</Typography>
        </Box>
      </Box>
    </React.Fragment>
  );
}
